### ISSUE TITLE
Errors out on Chrome

### ISSUE THREAD

**Issue by mrchief** [rmariuzzo/react-new-window#3]
Using the storybook, The popup opens and closes immediately.

![2018-01-18_12-04-44](https://user-images.githubusercontent.com/781818/35110867-da60f16e-fc47-11e7-8846-c73347e3c73b.gif)

I see these errors in the dev console:

```
Failed to load resource: the server responded with a status of 404 ()
preview.fb8859e8aaa4ba745d02.bundle.js:1 Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at https://rmariuzzo.github.io/react-new-window/static/preview.fb8859e8aaa4ba745d02.bundle.js:1:80592
    at Array.forEach (<anonymous>)
    at copyStyles (https://rmariuzzo.github.io/react-new-window/static/preview.fb8859e8aaa4ba745d02.bundle.js:1:80549)
    at NewWindow.value (https://rmariuzzo.github.io/react-new-window/static/preview.fb8859e8aaa4ba745d02.bundle.js:1:83794)
    at commitLifeCycles (https://rmariuzzo.github.io/react-new-window/static/preview.fb8859e8aaa4ba745d02.bundle.js:1:642216)
    at commitAllLifeCycles (https://rmariuzzo.github.io/react-new-window/static/preview.fb8859e8aaa4ba745d02.bundle.js:1:657638)
    at HTMLUnknownElement.callCallback (https://rmariuzzo.github.io/react-new-window/static/preview.fb8859e8aaa4ba745d02.bundle.js:1:493509)
    at Object.invokeGuardedCallback (https://rmariuzzo.github.io/react-new-window/static/preview.fb8859e8aaa4ba745d02.bundle.js:1:494007)
    at invokeGuardedCallback (https://rmariuzzo.github.io/react-new-window/static/preview.fb8859e8aaa4ba745d02.bundle.js:1:492025)
    at commitAllWork (https://rmariuzzo.github.io/react-new-window/static/preview.fb8859e8aaa4ba745d02.bundle.js:1:659223)
preview.fb8859e8aaa4ba745d02.bundle.js:1 The above error occurred in the <NewWindow> component:
    in NewWindow (created by DefaultStory)
    in div (created by Container)
    in Container (created by DefaultStory)
    in DefaultStory

Consider adding an error boundary to your tree to customize error handling behavior.
You can learn more about error boundaries at https://fb.me/react-error-boundaries.
```

**Comment by rmariuzzo** [comment]
Looks like copying styles from parent to new window is causing the issue...

**Comment by rmariuzzo** [comment]
I will take a look later. I'm on the phone right nowm

**Comment by jiadams** [comment]
Error might be to be tied to this ticket: https://bugs.dojotoolkit.org/ticket/19100. 

I tried to debug for a while but couldn't find a solution. Workaround is setting the copyStyles={false} in the props, and adding a style element manually but obviously this solution isn't ideal.

**Comment by Moshem123** [comment]
2 months for a phone call? :)
I fixed it and added a pull requests.
Waiting for it to be accepted.

**Comment by rmariuzzo** [comment]
Checking right now. I apologize for not coming back, got distracted.

**Comment by rmariuzzo** [comment]
@Moshem123 I reviewed your PR.
